"use client";

import Script from "next/script";
import { useActionState } from "react";
import { initialContactState, submitEnquiry } from "@/lib/contact-actions";

const labels: Record<string, string> = { general: "General business enquiry", technology_capability: "Technology capability", gcc: "GCC capability", workforce: "Technology workforce", engineering: "Engineering or product capability", quality_trust: "Quality engineering or digital trust", application_support: "Application support or reliability", other: "Other business enquiry" };
const solutionOptions = [["build","Build"],["scale","Scale"],["engineer","Engineer"],["assure","Assure"],["operate","Operate"],["evolve","Evolve"]];
const capabilityOptions = [["workforce","Workforce"],["digital_engineering","Digital Engineering"],["digital_trust","Digital Trust"],["emerging_technology","Emerging Technology"],["application_support","Application Support"],["quality_engineering","Quality Engineering"]];

export function ContactForm({ intent, source }: { intent: string; source: string }) {
  const safeIntent = Object.hasOwn(labels, intent) ? intent : "general"; const [state, action, pending] = useActionState(submitEnquiry, initialContactState); const siteKey = process.env.NEXT_PUBLIC_TURNSTILE_SITE_KEY; const error = (field: string) => state.fieldErrors?.[field]?.[0];
  if (state.ok && !state.preview) return <div className="form-success" role="status"><span>Enquiry received</span><h2>Thanks. We have what we need.</h2><p>{state.message}</p><p>The Progience lead closest to your challenge will review it.</p></div>;
  return <>{siteKey && <Script src="https://challenges.cloudflare.com/turnstile/v0/api.js" strategy="afterInteractive" />}<form action={action} className="contact-form" noValidate>
    <div className="form-heading"><span>Your conversation</span><h2>Tell us what needs to change.</h2><p>Share enough context for us to bring the right person into the room.</p></div><input type="hidden" name="sourceContext" value={source} /><div className="honeypot" aria-hidden="true"><label>Company website<input name="companyWebsite" tabIndex={-1} autoComplete="off" /></label></div>
    <div className="field full"><label htmlFor="enquiryType">What would you like to discuss?</label><select id="enquiryType" name="enquiryType" defaultValue={safeIntent}>{Object.entries(labels).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></div>
    <fieldset className="choice-group full"><legend>Which outcomes are most relevant? <span>Optional</span></legend><div>{solutionOptions.map(([value,label])=><label key={value}><input type="checkbox" name="solutionInterest" value={value}/><span>{label}</span></label>)}</div></fieldset>
    <fieldset className="choice-group full"><legend>Which capabilities may be involved? <span>Optional</span></legend><div>{capabilityOptions.map(([value,label])=><label key={value}><input type="checkbox" name="capabilityInterest" value={value}/><span>{label}</span></label>)}</div></fieldset>
    <div className="field"><label htmlFor="fullName">Full name</label><input id="fullName" name="fullName" autoComplete="name" required aria-describedby={error("fullName")?"fullName-error":undefined}/>{error("fullName")&&<span id="fullName-error" className="field-error">{error("fullName")}</span>}</div><div className="field"><label htmlFor="workEmail">Work email</label><input id="workEmail" name="workEmail" type="email" autoComplete="email" required aria-describedby={error("workEmail")?"workEmail-error":undefined}/>{error("workEmail")&&<span id="workEmail-error" className="field-error">{error("workEmail")}</span>}</div>
    <div className="field"><label htmlFor="company">Company</label><input id="company" name="company" autoComplete="organization"/></div><div className="field"><label htmlFor="jobTitle">Job title</label><input id="jobTitle" name="jobTitle" autoComplete="organization-title"/></div><div className="field"><label htmlFor="phone">Phone <span>Optional</span></label><input id="phone" name="phone" type="tel" autoComplete="tel"/></div><div className="field"><label htmlFor="country">Country or region</label><input id="country" name="country" autoComplete="country-name"/></div>
    <div className="field full"><label htmlFor="message">What is the context and desired outcome?</label><textarea id="message" name="message" rows={6} required aria-describedby={error("message")?"message-error":undefined}/>{error("message")&&<span id="message-error" className="field-error">{error("message")}</span>}</div>
    <label className="check-field full"><input type="checkbox" name="consentPrivacy" required/><span>I have read the <a href="/privacy" target="_blank">privacy notice</a> and agree to the use of my information to respond to this enquiry.</span></label><label className="check-field full"><input type="checkbox" name="consentMarketing"/><span>I would like to receive occasional relevant Progience insights. This is optional.</span></label>
    {siteKey && <div className="cf-turnstile full" data-sitekey={siteKey} data-theme="light" />}{state.message && <p className={`form-message full ${state.ok?"success":"error"}`} aria-live="polite">{state.message}</p>}<button className="button button-primary form-submit" type="submit" disabled={pending}>{pending?"Routing your enquiry…":"Submit enquiry"}</button>
  </form></>;
}
