import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, CheckCircle2 } from "lucide-react";
import { ContextualCTA, PageHero, SectionIntro } from "@/components/ui";

export const metadata: Metadata = { title: "About", description: "Progience is a Technology Capability Partner connecting people, engineering, quality, trust and operations around customer outcomes." };
export default function AboutPage() { return <main><PageHero eyebrow="Who we are" title="Technology capability, connected around progress." intro="Progience brings together specialist people and technology disciplines to help organisations build, scale and evolve the capability required for execution." crumbs={[{ label: "About" }]} />
  <section className="section"><div className="shell split-grid"><SectionIntro eyebrow="Our role" title="A technology partner built around the work." body="We start with the outcome and assemble the capabilities needed to deliver it. That keeps the conversation grounded in the customer’s world." /><div className="reason-grid vertical">{["Understand the problem","Shape the right capability mix","Back important claims with evidence","Make the next step clear"].map((item)=><div key={item}><CheckCircle2 aria-hidden="true"/><strong>{item}</strong></div>)}</div></div></section>
  <section className="section section-mist"><div className="shell"><SectionIntro eyebrow="Company story" title="Experience should make the next outcome more credible." body="Progience was founded in 2013. The public story will focus on what that experience enables for customers today rather than presenting a chronology for its own sake." /><div className="about-link-grid"><Link href="/about/why-progience"><span>Differentiation</span><h3>Why Progience</h3><p>How connected capability, enterprise discipline and evidence shape the proposition.</p><ArrowRight/></Link><Link href="/about/enterprise-readiness"><span>Trust</span><h3>Enterprise readiness</h3><p>How governance, quality, privacy and operational discipline support engagement.</p><ArrowRight/></Link></div></div></section>
  <section className="section section-navy"><div className="shell"><SectionIntro eyebrow="How capability becomes execution" title="Context → architecture → mobilisation → evidence → evolution" body="Progience engagements should make the capability design, working model, governance and evidence path explicit." /><div className="process-grid">{["Understand context","Shape capability","Mobilise delivery","Establish proof","Evolve responsibly"].map((item,index)=><div key={item}><span>{String(index+1).padStart(2,"0")}</span><h3>{item}</h3></div>)}</div></div></section>
  <ContextualCTA title="Learn how Progience could support your technology capability." body="Start with the challenge, current context and outcome you want to change." href="/contact?intent=technology_capability&source=about" label="Start a conversation" />
  </main>; }
