import type { Metadata } from "next";
import Link from "next/link";
import { ContextualCTA, PageHero, SectionIntro } from "@/components/ui";
import { openRoles } from "@/lib/content";

export const metadata: Metadata = { title: "Careers", description: "Explore life, learning and career opportunities at Progience.", alternates: { canonical: "/careers" } };
export default function CareersPage(){return <main><PageHero eyebrow="Careers at Progience" title="Do good work. Keep getting better at it." intro="This is where candidates can learn about life at Progience and find approved open roles. Client workforce enquiries have their own separate route." crumbs={[{label:"Careers"}]} />
  <section className="section"><div className="shell"><SectionIntro eyebrow="Why join" title="Work that values capability, ownership and learning."/><div className="reason-card-grid">{[["Meaningful engineering","Contribute to real technology outcomes and complex customer problems."],["Continuous learning","Develop capability through practice, feedback and collaboration."],["Ownership","Take responsibility for quality, communication and delivery."],["Respect and inclusion","Help create an environment where people can contribute and grow."]].map(([title,body])=><div key={title}><h2>{title}</h2><p>{body}</p></div>)}</div></div></section>
  <section className="section section-mist"><div className="shell"><SectionIntro eyebrow="Open roles" title="Current opportunities" body="Only approved, active roles are published."/>{openRoles.length ? <div>{openRoles.map((role)=><Link key={role.slug} href={`/careers/roles/${role.slug}`}>{role.title}</Link>)}</div>:<div className="empty-state compact"><h3>No approved roles are currently published.</h3><p>Please check again later. General business enquiries are not routed to the talent team.</p></div>}</div></section>
  <section className="section"><div className="shell"><SectionIntro eyebrow="Hiring process" title="A clear, candidate-first journey."/><div className="comparison-flow">{[["Apply","Submit to a specific approved role."],["Review","The talent team assesses relevant experience."],["Conversations","Meet the people connected to the role."],["Decision","Receive a clear outcome and next steps."]].map(([title,body],index)=><div key={title}><span>{String(index+1).padStart(2,"0")}</span><strong>{title}</strong><p>{body}</p></div>)}</div></div></section>
  <ContextualCTA eyebrow="Client enquiry?" title="Looking for technology workforce capability instead?" body="Workforce Services is a customer capability. Careers is only for candidates and job applications." href="/contact?intent=workforce&source=careers" label="Explore workforce needs" />
  </main>}
