import type { Metadata } from "next";
import Link from "next/link";
import { CheckCircle2 } from "lucide-react";
import { ContextualCTA, PageHero, SectionIntro } from "@/components/ui";

export const metadata: Metadata = { title: "Enterprise Readiness", description: "The governance, quality, security, privacy and operational disciplines considered in Progience engagements." };
const areas=["Governance and accountability","Quality management","Security and digital trust","Privacy and consent","Operational resilience","Access and change control","Evidence and auditability","Responsible capability claims"];
export default function EnterpriseReadinessPage(){return <main><PageHero eyebrow="Trust and governance" title="Enterprise confidence requires visible discipline." intro="This page describes the readiness areas Progience expects enterprise buyers to evaluate. Named certifications or credentials will appear only when scope and validity are verified." crumbs={[{label:"About",href:"/about"},{label:"Enterprise readiness"}]} />
  <section className="section"><div className="shell"><SectionIntro eyebrow="Evaluation areas" title="Trust should be inspectable." body="The precise controls and evidence depend on the engagement. These areas define the questions that must be answered."/><div className="reason-card-grid">{areas.map((item)=><div key={item}><CheckCircle2 aria-hidden="true"/><h2>{item}</h2><p>Confirm the accountable owner, operating process, supporting evidence and review cycle appropriate to the engagement.</p></div>)}</div></div></section>
  <section className="section section-navy"><div className="shell split-grid"><SectionIntro eyebrow="Credentials and claims" title="Verification controls the wording." body="Certifications, partnerships, customer evidence and formal governance claims remain category-level until scope, ownership and current validity are approved."/><div className="note-panel dark"><strong>Publication status</strong><p>This launch version deliberately avoids named enterprise credentials that were not supplied in the approved proof inventory.</p></div></div></section>
  <section className="section"><div className="shell split-grid"><SectionIntro eyebrow="Website trust" title="The website follows the same discipline." body="Secure forms, data minimisation, consent separation, private résumé storage, access controls, security headers and monitored dependencies are part of the implementation baseline."/><div><Link className="text-link" href="/privacy">Privacy approach <span aria-hidden="true">→</span></Link><br/><Link className="text-link" href="/security">Website security <span aria-hidden="true">→</span></Link></div></div></section>
  <ContextualCTA title="What enterprise-readiness evidence do you require?" body="Share the evaluation context so the relevant governance, security or delivery owners can respond." href="/contact?intent=technology_capability&source=enterprise-readiness" label="Discuss enterprise readiness" />
  </main>}

