import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ContextualCTA, PageHero, SectionIntro } from "@/components/ui";
import { getInsight, insights } from "@/lib/content";

type Props = { params: Promise<{ category: string; slug: string }> };
export function generateStaticParams() { return insights.map(({ category, slug }) => ({ category, slug })); }
export async function generateMetadata({ params }: Props): Promise<Metadata> { const { category, slug } = await params; const item = getInsight(category, slug); if (!item) return {}; return { title: item.title, description: item.summary, openGraph: { type: "article", title: item.title, description: item.summary, images: ["/og.png"] }, twitter: { title: item.title, description: item.summary, images: ["/og.png"] } }; }
export default async function InsightPage({ params }: Props) { const { category, slug } = await params; const item = getInsight(category, slug); if (!item) notFound(); return <main><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify({ "@context": "https://schema.org", "@type": "Article", headline: item.title, description: item.summary, mainEntityOfPage: `https://progience.com/insights/${item.category}/${item.slug}`, author: { "@id": "https://progience.com/#organization" }, publisher: { "@id": "https://progience.com/#organization" }, image: "https://progience.com/og.png", inLanguage: "en" }).replace(/</g, "\\u003c") }} /><PageHero eyebrow={item.category.replaceAll("-"," ")} title={item.title} intro={item.summary} crumbs={[{ label: "Insights", href: "/insights" }, { label: item.title }]} />
  <article className="section article"><div className="shell article-grid"><aside><span>In this perspective</span><a href="#question">The question</a><a href="#framework">Practical framework</a><a href="#application">Applying it</a></aside><div className="article-body"><section id="question"><p className="eyebrow dark">The question</p><h2>{item.question}</h2><p>Technology capability problems are rarely solved by adding one isolated service. The more useful starting point is to understand the intended outcome, the constraint that prevents it, and the disciplines that must work together.</p></section><section id="framework"><SectionIntro eyebrow="Practical framework" title="A disciplined way to move forward." /><ol className="framework-list">{item.framework.map((step, index) => <li key={step}><span>{String(index+1).padStart(2,"0")}</span><div><h3>{step}</h3><p>Define what this stage means in the organisation’s context, identify evidence, and agree how progress will be assessed before expanding scope.</p></div></li>)}</ol></section><section id="application"><SectionIntro eyebrow="Application" title="Connect the framework to capability and proof." body="Use the framework to clarify which workforce, engineering, quality, trust, support or emerging-technology capabilities are genuinely required. Strong claims should follow evidence rather than precede it." /><Link className="button button-navy" href="/capabilities">Explore capabilities</Link></section></div></div></article>
  <ContextualCTA title="How does this question show up in your organisation?" body="Share the context and outcome. Progience will route the conversation to the most relevant capability area." href={`/contact?intent=technology_capability&source=insights/${item.category}/${item.slug}`} label="Discuss the issue" />
  </main>; }
